name: aura_prueba
description: Versión de prueba de Aura Estándar
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  fl_chart: ^0.68.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.5
  share_plus: ^7.2.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/aura.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/aura.png"
  min_sdk_android: 21